### ISSUE TITLE
WHY CAN MY MOM GO THROUGH AN AIRLOCK??!!!

### ISSUE THREAD

**Issue by ACESTOACES** [murder357/SS-2003#2]
SHE DOES NOT FIT IN REAL LIFE!!

https://user-images.githubusercontent.com/117318569/199610183-e1312f4c-c1d0-4e8c-aaea-fa72a5e8e335.mp4

**Comment by murder357** [comment]
CAUSE SHES DEAD!!! PUSSY!!
